apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: whale-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: customer-service
      app: whale-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: customer-service
        app: whale-app
    spec:
      containers:
        - name: customer-service
          image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
